services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - UID=${UID}
        - GID=${GID}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./:/workspace
    user: "${UID}:${GID}"
    tty: true
    depends_on:
      - db
  ansible:
    build:
      context: .
      dockerfile: ./docker/ansible/Dockerfile
      args:
        - USERNAME=${USERNAME}
        - GROUPNAME=${GROUPNAME}
        - UID=${UID}
        - GID=${GID}
    volumes:
      - "$SSH_AUTH_SOCK:/tmp/ssh-agent.sock"
      - "~/.ssh/:/workspace/.ssh/"
      - "./infra/ansible:/workspace/ansible"
      - "./infra/vagrant:/workspace/vagrant"
    environment:
      SSH_AUTH_SOCK: "/tmp/ssh-agent.sock"
    tty: true
    working_dir: /workspace
    user: "${UID}:${GID}"
